apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana_img # tag that we gave to the docker image when we build it
        imagePullPolicy: IfNotPresent # allow to pull a local docker image
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep grafana'
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP