apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img # tag that we gave to the docker image when we build it
        imagePullPolicy: IfNotPresent # allow to pull a local docker image
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep vsftpd'
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21101
        - containerPort: 21100
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.64.9
  ports:
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftps-data
      protocol: TCP
      port: 20
      targetPort: 20
    - name: ftps-psv1
      protocol: TCP
      port: 21101
      targetPort: 21101
    - name: ftps-psv2
      protocol: TCP
      port: 21100
      targetPort: 21100